spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
        

  
mybatis:
  mapper-locations: classpath:static/mapper/*.xml            #XML文件
  
    